# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ship',
            name='flag',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='ship',
            name='imo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='IMO'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='mmsi',
            field=models.CharField(max_length=9, unique=True, verbose_name='MMSI'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fishing'), (2, 'Container'), (3, 'Tanker'), (4, 'Passanger'), (5, 'Sailing')]),
        ),
    ]
