# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_auto_20170411_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='begining_time',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='end_time',
        ),
        migrations.AddField(
            model_name='voyage',
            name='eta',
            field=models.DateTimeField(default='2012-12-12 12:12:12', verbose_name='Estimated Time of Arrival'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyage',
            name='etd',
            field=models.DateTimeField(default='2012-12-12 12:12:12', verbose_name='Estimated Time of Departure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='type',
            field=models.IntegerField(choices=[(1, 'General Cargo'), (2, 'Container'), (3, 'Bulk Carrier'), (4, 'RO-RO'), (5, 'Product Tanker'), (6, 'Crude Tanker'), (7, 'LNG Tanker'), (8, 'Chemical Tanker'), (9, 'Heavy Lift'), (10, 'Sailing'), (11, 'Passenger'), (12, 'Tug'), (13, 'Fishing'), (14, 'Other')]),
        ),
    ]
